Main: Game.class
Player.class: Game.class Row.java Player.java
	javac Player.java
Solver.class: Row.class Solver.java Game.class
	javac Solver.java
Game.class: Row.class Game.java
	javac Game.java
Row.class: Row.java
	javac Row.java
run:
	java Solver
